#!/bin/bash

set -e

TARGET="autoall bozoconf brev rev count countsort cptobackup cvsstat index maketags mvtobackup percent repozclean revtail scramble vimall"


cleanoldreleasesingledir() {
    CLEANTARGET="${*}"
    CLEANPREFIX=".old_"

    for FILE in ${CLEANTARGET}
    do
	if [ -x "${FILE}" ]
	then
	    mv "${FILE}" "${CLEANPREFIX}${FILE}"
	fi
    done
}


cleanoldrelease() {
    CLEANTARGET="${*}"

    cat /etc/passwd | cut -d: -f6 | while read NOM
    do
	for DDIR in bin local/bin
	do
	    if [ -d "${NOM}/${DDIR}" ]
	    then
		(
		    cd "${NOM}/${DDIR}"
		    cleanoldreleasesingledir ${CLEANTARGET}
		)
	    fi
	done
    done
    for DDIR in /usr/local/bin /usr/local/sbin
    do
	    if [ -d "${DDIR}" ]
	    then
		(
		    cd "${DDIR}"
		    cleanoldreleasesingledir ${CLEANTARGET}
		)
	    fi
    done
}


. /usr/share/debconf/confmodule
db_get bozomake/purgeoldscriptinhomedir
if [ "$RET" = true ]; then
    cleanoldrelease ${TARGET}
fi
